version: 2
jobs:
  build:
    working_directory: ~/RagtagOpen/style-guide
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    docker:
      - image: circleci/ruby:2.3.7
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
      - run:
          "bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          --jobs=4 --retry=3 "
      - run: bundle exec jekyll build
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.bundle
            - ~/.go_workspace
            - ~/.gradle
            - ~/.cache/bower
      - run: bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external --empty-alt-ignore
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq install awscli
      - run:
          name: Invalidate CloudFront distro for brand.ragtag.org
          command: |
            aws cloudfront create-invalidation --distribution-id E1JSJN131ANO47 --paths '/*'
      - run:
          name: Copy assets folder to assets.ragtag.tech
          command: |
            aws s3 sync ./assets/ s3://assets.ragtag.tech/ --acl public-read
      - run:
          name: Invalidate CloudFront distribution for assets.ragtag.tech
          command: |
            aws cloudfront create-invalidation --distribution-id E1N1GBDQRP84YH --paths '/*'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
